#image: docker/compose:1.29.2
image: tmaier/docker-compose:latest

stages:
  - build
  - test

variables:
  #DOCKER_HOST: "tcp://docker:2375/"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind 

before_script:
  # - docker context ls
  # - echo "Hello, $GITLAB_USER_LOGIN!"
  # - echo "This is Branch $CI_COMMIT_BRANCH"
  # - echo $DOCKER_HOST
  # - docker-compose -v
  # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # - docker info

docker-build:
  stage: build  
  script:
    - echo "Building"
    - docker-compose build
  # Disable Build Path atm. Enable again by changing ``Dockerfile`` to ``dockerfile``  
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile


Docker-test:
  stage: test
  script:
    - echo "Testing"
    - echo $PYTHON_VERSION
    - apk add python3 py3-pip musl-dev alpine-sdk python3-dev 
    - pip3 install --upgrade pip
    - pip3 install --no-cache-dir numpy requests flask flask_cors
    - cd group03_ett/
    - python3 -m test_main
    - python3 -m test_ett_predictor

