version: '3'
services:
    webserver:
        ports:
            - 8080:80
        volumes:
            - ./html:/usr/local/apache2/htdocs/
            - ./docs/_build/html:/usr/local/apache2/htdocs/docs
        build:
            context: .
            target: webserver
    base:
        ports:
            - 8081:5000
        stdin_open: true
        tty: true
        build:
            context: .
            target: base
